spring:
  devtools: true
  flyway:
    locations: classpath:/db_migrations
    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/vs_template?searchpath=public
    username: postgres
    password: 123456
    maxLifetime: 0
    maxPoolSize: 500
  jooq:
    sql-dialect: POSTGRES
  resources:
    static-locations: classpath:/webapp/